### ISSUE TITLE
As the readme.md says there should be a rib and a spar system for the wing.

### ISSUE THREAD

**Issue by aapolipponen** [aapolipponen/fullcontrol-airfoil#3]
The code should be able to generate fully or mostly filled airfoils that can be used to support the wing. See the ideas about that in the documentation for airfoil_loft.py in the Readme.md

**Comment by aapolipponen** [comment]
I'm going to work on this soon. I have a prototype for a filling system but it's not ready yet. I'm not going to rush it because its pretty complicated. The spar system is coming faster. It's basically just a system to cut out a circle with a variable radius in points that you choose.

**Comment by aapolipponen** [comment]
The spar system is now partly added. Only problem is the circles are not that durable. (Not tested yet.) But I guess that can be solved by placing a second or even third circle with line_width added to the radius of the circle. This is basically what traditional slicers do. Also the part in which the circle is printed may vary in the future. I'm trying to have as little as possible travel lines. Fc.travel_to doesn't for some reason work properly. Some part of the code throws an error that all the z points aren't able to be gotten. But travel moves probably should be not used because of vase mode being implemented at some point.

**Comment by fullcontrol-xyz** [comment]
Good progress. For the circles, one weight-saving approach is to print a wave-like internal lattice (see below). This can be done very simply by printing to alternating small/large radii at, say, 20 points around a circle. Or if your circles are printed as, say, 20-sided polygons, you can print to alternating points in each circle to get the same effect.


For fc.travel_to(), make sure you're providing it with a fc.Point() and not a list of steps. Does that solve the problem? But I agree, if at all possible, avoid travel moves entirely. It makes toolpath-design more challenging but will ultimately achieve a better printing procedure and physical part.

![image](https://github.com/aapolipponen/fullcontrol-airfoil/assets/129191348/effcd743-ce51-42ad-8a25-19eab9aa8f1d)

Travel-free lattice-circle:
![image](https://github.com/aapolipponen/fullcontrol-airfoil/assets/129191348/3e89f77d-cf1c-4612-9b9b-81bbafb20773)

**Comment by aapolipponen** [comment]
I'm going to implement that. For the travel moves, I am trying to append them to a list and am providing them with a fc.Point. I will probably still do the wing for now at least without travel moves. I forgot to respond to the issue I created about raising the z. The code you provided worked. Also make sure to look at the updated README.md so you can see the full changes with the beta version. The changes are at airfoil_loft_infill_beta.py section. I'm going to change the naming scheme soon. I'm just going to basically just delete the other ones and call the file main.py and the other parts with mostly their current names.

**Comment by fullcontrol-xyz** [comment]
Ah, with fc.travel_to, it return a series of steps - *turn extruder off, move to point, turn extruder on* - so you need to extend your list rather than append to it

Sounds good with the other stuff.

**Comment by aapolipponen** [comment]
The problem was because of a function just not getting the coordinates from the fc.travel_to, was an easy fix. Still I am trying not to implement travel.

**Comment by aapolipponen** [comment]
Eh, actually I will probably use travel. The system creates too much useless lines. The circle zigzag fill system will be kept but I will just use travel, but still try to minimize it. I'm maybe going to create a toggle for that actually.

**Comment by fullcontrol-xyz** [comment]
Yeh sometimes it's difficult to avoid using travel entirely, but just make sure you try to avoid it where possible. And try to avoid it at critical regions. E,g, don't travel to the start of the outer perimeter line and immediately start printing it, since any defects will affect aerodynamics. Instead, travel to the inner line and print that so defects are kept inside where they're not as important.

**Comment by aapolipponen** [comment]
The rib system will be added soon. The problem is that I have two different versions of the whole project with both having some additions so I will have to go trough them to add both of the changes from the computers. That is why I haven't pushed much changes in some time because the different versions interfear and so on.

**Comment by aapolipponen** [comment]
The rib system is just a fill for a set layer. The fill goes in a set angle in lines. I probably could make a system for filling a perimeter first for example two times and then doing a fill in lines, like traditional slicers do.

**Comment by aapolipponen** [comment]
The rib system is now merged. This is done.
